# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
export PATH=/home/muhang.zb/pha-all/arcanist/bin/:$PATH
export PATH=/home/muhang.zb/mybin:$PATH

# User define command

alias mpwait="sh ~/wait.sh"
